-- This module is the root of the BuzzardGeeConjectureCanonicalLaneLean Lean proof package.
import BuzzardGeeConjectureCanonicalLaneLean.Basic
import BuzzardGeeConjectureCanonicalLaneLean.SourcePackage
import BuzzardGeeConjectureCanonicalLaneLean.SourceDependencies
import BuzzardGeeConjectureCanonicalLaneLean.Formalization
import BuzzardGeeConjectureCanonicalLaneLean.ReviewerBridge
import BuzzardGeeConjectureCanonicalLaneLean.TheoremStatement
import BuzzardGeeConjectureCanonicalLaneLean.MathlibObjects
import BuzzardGeeConjectureCanonicalLaneLean.AdmissibleClass
import BuzzardGeeConjectureCanonicalLaneLean.Projection
import BuzzardGeeConjectureCanonicalLaneLean.BridgeLemmas
import BuzzardGeeConjectureCanonicalLaneLean.GateLemmas
import BuzzardGeeConjectureCanonicalLaneLean.FinalTheorem
import BuzzardGeeConjectureCanonicalLaneLean.MathlibStatement
